/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookBookRouteImport } from './routes/book.$book'
import { Route as BookBookChapterRouteImport } from './routes/book.$book.$chapter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookRoute = BookBookRouteImport.update({
  id: '/book/$book',
  path: '/book/$book',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookChapterRoute = BookBookChapterRouteImport.update({
  id: '/$chapter',
  path: '/$chapter',
  getParentRoute: () => BookBookRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book/$book': typeof BookBookRouteWithChildren
  '/book/$book/$chapter': typeof BookBookChapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book/$book': typeof BookBookRouteWithChildren
  '/book/$book/$chapter': typeof BookBookChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book/$book': typeof BookBookRouteWithChildren
  '/book/$book/$chapter': typeof BookBookChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/book/$book' | '/book/$book/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/book/$book' | '/book/$book/$chapter'
  id: '__root__' | '/' | '/book/$book' | '/book/$book/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookBookRoute: typeof BookBookRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$book': {
      id: '/book/$book'
      path: '/book/$book'
      fullPath: '/book/$book'
      preLoaderRoute: typeof BookBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$book/$chapter': {
      id: '/book/$book/$chapter'
      path: '/$chapter'
      fullPath: '/book/$book/$chapter'
      preLoaderRoute: typeof BookBookChapterRouteImport
      parentRoute: typeof BookBookRoute
    }
  }
}

interface BookBookRouteChildren {
  BookBookChapterRoute: typeof BookBookChapterRoute
}

const BookBookRouteChildren: BookBookRouteChildren = {
  BookBookChapterRoute: BookBookChapterRoute,
}

const BookBookRouteWithChildren = BookBookRoute._addFileChildren(
  BookBookRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookBookRoute: BookBookRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
