/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioControlX9k2RouteImport } from './routes/studio-control-x9k2'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerseMeaningsIndexRouteImport } from './routes/verse-meanings.index'
import { Route as SummaryIndexRouteImport } from './routes/summary.index'
import { Route as BookBookIndexRouteImport } from './routes/book.$book.index'
import { Route as SummaryBookChapterRouteImport } from './routes/summary.$book.$chapter'
import { Route as BookBookChapterRouteImport } from './routes/book.$book.$chapter'
import { Route as VerseMeaningsBookChapterVerseRouteImport } from './routes/verse-meanings.$book.$chapter.$verse'

const StudioControlX9k2Route = StudioControlX9k2RouteImport.update({
  id: '/studio-control-x9k2',
  path: '/studio-control-x9k2',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerseMeaningsIndexRoute = VerseMeaningsIndexRouteImport.update({
  id: '/verse-meanings/',
  path: '/verse-meanings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryIndexRoute = SummaryIndexRouteImport.update({
  id: '/summary/',
  path: '/summary/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookIndexRoute = BookBookIndexRouteImport.update({
  id: '/book/$book/',
  path: '/book/$book/',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryBookChapterRoute = SummaryBookChapterRouteImport.update({
  id: '/summary/$book/$chapter',
  path: '/summary/$book/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookChapterRoute = BookBookChapterRouteImport.update({
  id: '/book/$book/$chapter',
  path: '/book/$book/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const VerseMeaningsBookChapterVerseRoute =
  VerseMeaningsBookChapterVerseRouteImport.update({
    id: '/verse-meanings/$book/$chapter/$verse',
    path: '/verse-meanings/$book/$chapter/$verse',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRoute
  '/settings': typeof SettingsRoute
  '/studio-control-x9k2': typeof StudioControlX9k2Route
  '/summary/': typeof SummaryIndexRoute
  '/verse-meanings/': typeof VerseMeaningsIndexRoute
  '/book/$book/$chapter': typeof BookBookChapterRoute
  '/summary/$book/$chapter': typeof SummaryBookChapterRoute
  '/book/$book/': typeof BookBookIndexRoute
  '/verse-meanings/$book/$chapter/$verse': typeof VerseMeaningsBookChapterVerseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRoute
  '/settings': typeof SettingsRoute
  '/studio-control-x9k2': typeof StudioControlX9k2Route
  '/summary': typeof SummaryIndexRoute
  '/verse-meanings': typeof VerseMeaningsIndexRoute
  '/book/$book/$chapter': typeof BookBookChapterRoute
  '/summary/$book/$chapter': typeof SummaryBookChapterRoute
  '/book/$book': typeof BookBookIndexRoute
  '/verse-meanings/$book/$chapter/$verse': typeof VerseMeaningsBookChapterVerseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRoute
  '/settings': typeof SettingsRoute
  '/studio-control-x9k2': typeof StudioControlX9k2Route
  '/summary/': typeof SummaryIndexRoute
  '/verse-meanings/': typeof VerseMeaningsIndexRoute
  '/book/$book/$chapter': typeof BookBookChapterRoute
  '/summary/$book/$chapter': typeof SummaryBookChapterRoute
  '/book/$book/': typeof BookBookIndexRoute
  '/verse-meanings/$book/$chapter/$verse': typeof VerseMeaningsBookChapterVerseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/books'
    | '/settings'
    | '/studio-control-x9k2'
    | '/summary/'
    | '/verse-meanings/'
    | '/book/$book/$chapter'
    | '/summary/$book/$chapter'
    | '/book/$book/'
    | '/verse-meanings/$book/$chapter/$verse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/books'
    | '/settings'
    | '/studio-control-x9k2'
    | '/summary'
    | '/verse-meanings'
    | '/book/$book/$chapter'
    | '/summary/$book/$chapter'
    | '/book/$book'
    | '/verse-meanings/$book/$chapter/$verse'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/books'
    | '/settings'
    | '/studio-control-x9k2'
    | '/summary/'
    | '/verse-meanings/'
    | '/book/$book/$chapter'
    | '/summary/$book/$chapter'
    | '/book/$book/'
    | '/verse-meanings/$book/$chapter/$verse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BooksRoute: typeof BooksRoute
  SettingsRoute: typeof SettingsRoute
  StudioControlX9k2Route: typeof StudioControlX9k2Route
  SummaryIndexRoute: typeof SummaryIndexRoute
  VerseMeaningsIndexRoute: typeof VerseMeaningsIndexRoute
  BookBookChapterRoute: typeof BookBookChapterRoute
  SummaryBookChapterRoute: typeof SummaryBookChapterRoute
  BookBookIndexRoute: typeof BookBookIndexRoute
  VerseMeaningsBookChapterVerseRoute: typeof VerseMeaningsBookChapterVerseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio-control-x9k2': {
      id: '/studio-control-x9k2'
      path: '/studio-control-x9k2'
      fullPath: '/studio-control-x9k2'
      preLoaderRoute: typeof StudioControlX9k2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verse-meanings/': {
      id: '/verse-meanings/'
      path: '/verse-meanings'
      fullPath: '/verse-meanings/'
      preLoaderRoute: typeof VerseMeaningsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary/': {
      id: '/summary/'
      path: '/summary'
      fullPath: '/summary/'
      preLoaderRoute: typeof SummaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$book/': {
      id: '/book/$book/'
      path: '/book/$book'
      fullPath: '/book/$book/'
      preLoaderRoute: typeof BookBookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary/$book/$chapter': {
      id: '/summary/$book/$chapter'
      path: '/summary/$book/$chapter'
      fullPath: '/summary/$book/$chapter'
      preLoaderRoute: typeof SummaryBookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$book/$chapter': {
      id: '/book/$book/$chapter'
      path: '/book/$book/$chapter'
      fullPath: '/book/$book/$chapter'
      preLoaderRoute: typeof BookBookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verse-meanings/$book/$chapter/$verse': {
      id: '/verse-meanings/$book/$chapter/$verse'
      path: '/verse-meanings/$book/$chapter/$verse'
      fullPath: '/verse-meanings/$book/$chapter/$verse'
      preLoaderRoute: typeof VerseMeaningsBookChapterVerseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BooksRoute: BooksRoute,
  SettingsRoute: SettingsRoute,
  StudioControlX9k2Route: StudioControlX9k2Route,
  SummaryIndexRoute: SummaryIndexRoute,
  VerseMeaningsIndexRoute: VerseMeaningsIndexRoute,
  BookBookChapterRoute: BookBookChapterRoute,
  SummaryBookChapterRoute: SummaryBookChapterRoute,
  BookBookIndexRoute: BookBookIndexRoute,
  VerseMeaningsBookChapterVerseRoute: VerseMeaningsBookChapterVerseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
